name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development"  ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:        
        runs-on: [ ubuntu-latest, macos-latest ]
        python-version: [ "3.10", "3.12" ] 

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python  ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ matrix.python-version }}

      - name: Test notebook
        env:
           CI: "true"
        run: |
          echo Testing notebook
          pip install biopython requests
          pip install pytest nbmake

          pytest -vs --nbmake --nbmake-kernel=python3  --nbmake-timeout=600 *.ipynb
